### DISCUSSION TITLE
v2.0.0

### DISCUSSION THREAD

**Discussion by markusthoemmes** [digitalocean/app_action#122] [Announcements]
This is a complete rewrite with the goal of being more orchestratable in a broader GitHub Actions context.

## 🚀 New Features

- Rewritten to use `godo` instead of shelling out to `doctl` for better error handling and overall control of the process.
- Supports picking up an in-repository (or filesystem really) `app.yaml` (defaults to `.do/app.yaml`, configurable via the `app_spec_location` input) to create the app from instead of having to rely on an already existing app that's then downloaded (though that is still supported). The in-filesystem app spec can also be templated with environment variables automatically (see examples below).
- Prints the build and deploy logs into the Github Action log (configurable via `print_build_logs` and `print_deploy_logs`) and surfaces them as outputs `build_logs` and `deploy_logs`.
- Provides the app's metadata as the output `app`.

## Breaking changes:

- The `images` input is no longer supported. Instead, use env-var-substitution for an in-repository app spec or the `IMAGE_DIGEST_$component-name`/`IMAGE_TAG_$component-name` environment variables to change the respective fields of images in an existing app.

## 👨🏼‍💻 Contributors

@markusthoemmes

<hr /><em>This discussion was created from the release <a href='https://github.com/digitalocean/app_action/releases/tag/v2.0.0'>v2.0.0</a>.</em>

**Comment by arimgibson** [comment]
Amazing work @markusthoemmes !! This is awesome - super appreciate the updated README.md, lots of cool functionality I wouldn't have figured out otherwise 🎉

**Comment by bensheldon** [comment]
>  or the IMAGE_DIGEST_$component-name/IMAGE_TAG_$component-name environment variables to change the respective fields of images in an existing app.

Can you explain how to use these? I'm really struggling to understand how to update for v2 where I only want to make a new deploy with an updated image.

**Reply by markusthoemmes** [reply]
So the idea is, if you have an existing app with a spec like this:

```yaml
name: sample
services:
- name: sample
  image:
    registry_type: GHCR
    registry: YOUR_ORG
    repository: YOUR_REPO
    tag: v1
```

and you want to update that to, say, v2, with those env vars, you'd set `IMAGE_TAG_SAMPLE=v2` as an env var like so

```yaml
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v2
        env:
          IMAGE_TAG_SAMPLE: v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          app_name: YOUR_APP_NAME
```

and it'll update accordingly. Please let me know if this helped, I'll update the README accordingly to be a little more verbose here.

**Reply by bensheldon** [reply]
Thanks for the help! 💖  

Given my v1 action has a step like this:

```yaml
- name: DigitalOcean App Platform deployment
  uses: digitalocean/app_action@v1.1.6
  with:
    app_name: dayoftheshirt
    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    images: | 
      [
        {
          "name": "dayoftheshirt-rails",
          "image": {
            "registry_type": "DOCR",
            "repository": "dayoftheshirt-rails",
            "tag": "${{ steps.short-sha.outputs.value }}"
          }
        }
      ]
```

I would update that for V2 to look like (from [the tests](https://github.com/digitalocean/app_action/blob/4ccabc61feeb8d953db705f44ef134f90655ea79/deploy/images_test.go#L40-L42) it looks like `-`hyphens in the service name should be converted to underscores in the ENV variable):

```yaml
- name: DigitalOcean App Platform deployment
  uses: digitalocean/app_action@v2
  with:
    app_name: dayoftheshirt
    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  env:
    IMAGE_TAG_DAYOFTHESHIRT_RAILS: "${{ steps.short-sha.outputs.value }}"
```

That seem right?

**Reply by markusthoemmes** [reply]
Yep, that looks spot on.

**Reply by bensheldon** [reply]
Thank you! That unblocks me 🙇🏻 I wonder if the upgrade guide could share a specific example like this of before and after for the ENV variables (and explain how to convert a service/component into an ENV).

**Reply by markusthoemmes** [reply]
Great! Yeah, I'll add some more verbiage there and include an example as well.

**Reply by bensheldon** [reply]
Thanks!

Also, you might call out in the upgrade docs that the GitHub Action name changed and needs to be updated, or else you'll get `Unexpected input(s) 'app_name', 'token', valid inputs are l'entryPoint', 'args']`

```diff
- uses: digitalocean/app_action@v1
+ uses: digitalocean/app_action/deploy@v2
```

Unfortunately not updating it won't fail the action, and it was very subtle change 😞

**Reply by markusthoemmes** [reply]
@bensheldon I've sent https://github.com/digitalocean/app_action/pull/125 to improve on the upgrade documentation. I'd love to get your feedback on it given you had a bit of pain here 🙏 .

**Comment by zeshuaro** [comment]
Is it expected that environment variables have to be defined in the new `.do/app.yaml` requirement in v2.0.0? If so, this is probably worth highlighting in the migration section, as I wasn't aware of this and lost all my environment variables after a deployment. 

And also feels a bit weird that I now have to store all the environment variables used in the DO app on GitHub and have them injected into the app spec, unless I'm doing something wrong.

**Reply by markusthoemmes** [reply]
The `.do/app.yaml` is supposed to contain **all** information for an app, yes. The app in the system will be overridden with whatever state is in that YAML, which makes it completely declarative. The intention here is to drive the entire lifecycle via Github. You don't have to store them as Github secrets though. If they're not secret, you can "just" store them in the repository in plain-text.

Alternatively, you can use an `app_name` based model, where you create the app with whichever state you want via other means (UI, doctl, terraform etc.) and only use the action to force-kick that app to redeploy or update images (as outlined in the README). In this case, I'd expect you to **not** check in the `.do/app.yaml`.

**Reply by zeshuaro** [reply]
Right, so what I should be using is the `app_name` based model. I got confused by the following section and assumed even with this model the app spec file still needs to be included:

<img width="862" alt="image" src="https://github.com/user-attachments/assets/ca9e7d76-af10-445a-89a0-b491116b427e">

Thanks for clarifying!

**Reply by BorisBarzotto** [reply]
Greetings, I am getting the following error, my deployment is failing: “error validating app spec field ‘services.image’: image reference cannot be parsed”. My APP SPECS in the control panel has a tag of an image in use defined, I want to update that value to the value of the new tag generated in the build, so in github actions I place IMAGE_TAG_SAMPLE_SERVICE = .... as you comment above, matching SAMPLE_SERVICE with the name of the service of my app in the app specs in Digital Ocean (I don't have an app spec yaml in my repo eg:.do/app.yaml). I don't understand very well the example of updating an image, i.e. adding this convention of IMAGE_TAG_SAMPLE_SERVICE for example look in the app spec inside DO for the services.image.tag field of the service named sample-service and modify it??.... I think I am missing something

**Reply by markusthoemmes** [reply]
@BorisBarzotto what's the name of the service in your app? What are you setting the env var to? Could you provide example snippets?

**Reply by BorisBarzotto** [reply]
Hi Markus! @markusthoemmes 
my app spec in DO is this: 
```
name: sea-lion-app
region: nyc
services:
- http_port: 8080
  image:
    registry: dann
    registry_credentials: ...my_credentials
    registry_type: DOCKER_HUB
    repository: solutions
    tag: sha-24be2e3
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: lanc-service
```
Github actions deploy step is:

```
- name: Deploy the app
   uses: digitalocean/app_action/deploy@v2
   env:
       IMAGE_TAG_LANC_SERVICE: ${{ steps.docker-meta.outputs.tags }}
   with:
       token: ${{ secrets.STAGING_DO_ACCESS_TOKEN }}
       app_name: sea-lion-app
```

${{ steps.docker-meta.outputs.tags }} is the build tag i get from step behind. I have also tried to hardcode a name here to try just in case.

```
app "sea-lion-app" already exists, updating...
Error: failed to deploy: failed to update app: PUT https://api.digitalocean.com/v2/apps/xxxxxxxx-c31e-40c4-xxxxxxxxxxxxxxxxx: 400 (request "xxxxxxxx-c9bb-4941-8f0d-xxxxxxxxxx") error validating app spec field "services.image": image reference cannot be parsed, check services.image.registry, services.image.repository, services.image.tag and/or services.image.digest
```

I can't get it to be referenced in the App Spec either, I tried with the notation ${....}. and the UI doesn't let me save it, it tells me that I shouldn't reference it this way, it doesn't allow me to save it.

thanks for your reply !
