### ISSUE TITLE
deploy@v2 doesn't build the application

### ISSUE THREAD

**Issue by bramdevries** [digitalocean/app_action#123]
## Context

We migrated from v1 to v2 today by making the following changes in our workflow and noticed that it 

**From**

```yaml
- name: DigitalOcean App Platform deployment (Acceptance env)
  uses: digitalocean/app_action@v1
  with:
    app_name: development-platform-app
    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
```

**To**

```yaml
- name: DigitalOcean App Platform deployment (Acceptance env)
  uses: digitalocean/app_action/deploy@v2
  with:
    app_name: development-platform-app
    token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
```

This went fine and we see the builds being triggered in App Platform but noticed that as of v2 it seems to only trigger a global app settings change and this skips the build entirely so any new changes are not actually being deployed. 

<img width="538" alt="image" src="https://github.com/user-attachments/assets/da38cc12-1b3e-4975-9e4b-be8359496108">

For comparison, the trigger on v1 was: 

<img width="514" alt="image" src="https://github.com/user-attachments/assets/83e3ff2f-06ba-4bea-b8a0-0fcf15c067ad">

In the actions log we see the following:

```
wait for deployment to finish
deployment is in phase: PENDING_BUILD
deployment is in phase: DEPLOYING
deployment is in phase: ACTIVE
```

We don't have an `app.yml` spec file in our repository as we are managing this elsewhere for each environment, and [the changelog](https://github.com/digitalocean/app_action/releases/tag/v2.0.0) also mentions that not providing a spec is still supported:

> Supports picking up an in-repository (or filesystem really) app.yaml (defaults to .do/app.yaml, configurable via the app_spec_location input) to create the app from instead of having to rely on an **already existing app that's then downloaded (though that is still supported)**
