### ISSUE TITLE
Deploy with image, errors on app creation, otherwise claims no image access

### ISSUE THREAD

**Issue by intel352** [digitalocean/app_action#130]
When no app exists in DO acct, running v2 deploy of an app with 2 services and 1 worker outputs the following:
```
app "core" does not exist yet, creating...
Error: failed to deploy: failed to create app: POST https://api.digitalocean.com/v2/apps: 409 (request "7f835d38-a2a1-40cc-88af-5e10b37c9461") App name already exists
```

When I check DO account, the app now exists, just isn't deployed.

If I run the job again:
```
app "core" already exists, updating...
Error: failed to deploy: failed to update app: PUT https://api.digitalocean.com/v2/apps/cb57496e-ccb8-45a6-ae28-aced510f6084: 500 (request "ba74a02d-9e5c-4b61-bd76-1e5773d05c91") Server Error; giving up after 5 attempt(s)
```

Giving up without actual details regarding what the error was is pretty useless.
If I go into DO interface, and attempt to use the Deploy button on the app, it then claims it doesn't have access to the image.

Some details:
- I have a Github org that I created which my repo exists within
- The DO app is installed in my org
- I created a personal access token (classic) to provide explicit read access to packages. I then pass `user:token` as credentials to my app.yaml to ensure DO has access to the built images

Here is my app.yaml:
```
name: core
ingress:
  rules:
    - component:
        name: manager
      match:
        path:
          prefix: /
    - component:
        name: runner
      match:
        path:
          prefix: /runner
region: nyc
services:
  - name: manager
    image:
      registry_type: GHCR
      registry: gocodealone
      repository: core
      registry_credentials: ${GHCR_CREDS} 
      digest: ${MANAGER_DIGEST}
    http_port: 9999
  - name: runner
    image:
      registry_type: GHCR
      registry: gocodealone
      repository: core
      registry_credentials: ${GHCR_CREDS}
      digest: ${RUNNER_DIGEST}
    http_port: 8888
workers:
  - name: orchestrator
    image:
      registry_type: GHCR
      registry: gocodealone
      repository: core
      registry_credentials: ${GHCR_CREDS}
      digest: ${ORCHESTRATOR_DIGEST}
```

When the run executes, I can see that each digest is indeed passed in as expected, as are my credentials:
```
Run digitalocean/app_action/deploy@v2
  with:
    token: ***
    print_build_logs: true
    print_deploy_logs: true
    app_spec_location: .do/app.yaml
    deploy_pr_preview: false
  env:
    GHCR_CREDS: intel352:***
    ORCHESTRATOR_DIGEST: sha256:bd81c30f851ce56dead4c01c24ede3dcbd722e4f1bd533d5f1b634a8d64cfc83
    MANAGER_DIGEST: sha256:11793823ab088e39800ad460b553d8cc66ab4753ba2dd8e2ce7b37f3b20fa080
    RUNNER_DIGEST: sha256:f2f89e4c288ad9db47c72e3f1dd6ebfcde6aad3d35cd7e7f45555e767440c8ed
```

Additionally, when I specify the print*logs options, I see no change to the output... So there's no additional logging that is enabled to help debug the actual problem.
