### ISSUE TITLE
App is not rebuilt

### ISSUE THREAD

**Issue by hillalex** [digitalocean/app_action#166]
[Edited - one of the issues was my error!]

Hi devs, thanks for providing this action. Unfortunately I am struggling with a previously identified issue: #123.

My action yaml contains the following step:
```yaml
    - name: Deploy
      uses: digitalocean/app_action/deploy@v2.0.6
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        app_name: seroviz
        print_deploy_logs: true
```

Expected behaviour:
* a rebuild and deploy is triggered

Actual behaviour:
* an app configuration update is triggered

See
![image](https://github.com/user-attachments/assets/b63c2a3f-29a3-4c9b-802c-5e1cfc7547a6)

Any help much appreciated!

**Comment by hillalex** [comment]
> Thanks for reaching out! Just to verify: Are you changing pieces of the source-code to warrant a rebuild or do you expect the app to be rebuilt regardless? If you could share the AppSpec (or the app ID) that'd be helpful.

Thanks for speedy reply! I'm pushing a new Docker image prior to triggering the deployment, so want the app platform to pull the new image and deploy. I'm a bit confused as to why an app configuration update is being triggered, as the app spec shouldn't change at all.

The full app spec:

```
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: seroviz.seroanalytics.org
  type: PRIMARY
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: serovizr
    match:
      path:
        prefix: /api
  - component:
      name: seroviz
    match:
      path:
        prefix: /
name: seroviz
region: lon
services:
- http_port: 8888
  image:
    registry: seroanalytics
    registry_type: DOCKER_HUB
    repository: serovizr
    tag: main
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: serovizr
- http_port: 80
  image:
    registry: seroanalytics
    registry_type: DOCKER_HUB
    repository: seroviz
    tag: main
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: seroviz
  ```
