### ISSUE TITLE
Action Builds Even If Ignored via `if` Condition

### ISSUE THREAD

**Issue by arimgibson** [digitalocean/app_action#171]
Not sure if this falls on y'all or GitHub Actions itself -- but the step created by this Action being used "Build digitalocean/app_platform/deploy@v2" is run even if the Action has an `if` condition associated with it that causes it to be skipped. Not a huge deal but adds some unnecessary delay to the CI/CD pipeline. Thanks!
```yaml
      - name: Deploy app to DigitalOcean App Platform
        if: matrix.app.type == 'BE'
        uses: digitalocean/app_action/deploy@v2
```
![image](https://github.com/user-attachments/assets/b9344dea-8d7a-46fc-9e9b-ad78143c68d4)
