### ISSUE TITLE
App Spec Not Updating

### ISSUE THREAD

**Issue by arimgibson** [digitalocean/app_action#172]
Having some issues with the action as it appears my app spec doesn't update, which results in an older version of my application being deployed ("latest" Docker tag instead of a specific tag associated with the commit). No errors are thrown by the action, though I am able to update it correctly with the same action via the `doctl`. Not really sure what's up here or any other context I can provide :grimacing: -- lmk, thank you!

.do/api.yaml
```yaml
alerts:
  - rule: DEPLOYMENT_LIVE
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: hidden
    type: PRIMARY
ingress:
  rules:
    - component:
        name: api
      match:
        path:
          prefix: /
name: hidden
region: nyc
services:
  - alerts:
      - operator: GREATER_THAN
        rule: CPU_UTILIZATION
        value: 80
        window: FIVE_MINUTES
      - operator: GREATER_THAN
        rule: MEM_UTILIZATION
        value: 80
        window: FIVE_MINUTES
    health_check:
      http_path: /health-check
      failure_threshold: 2
    http_port: 3001
    image:
      registry: joinvalley
      registry_credentials: hidden
      registry_type: GHCR
      repository: hidden
      tag: ${GHCR_TAG}
    instance_count: 1
    instance_size_slug: apps-s-2vcpu-4gb
    name: api
```

deploy.yml
```yaml
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy app to DigitalOcean App Platform
        if: matrix.app.type == 'BE'
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_API_KEY }}
          app_spec_location: .do/${{ matrix.app.name }}.yaml
          app_name: joinvalley-v2-${{ matrix.app.name }}
        env:
          GHCR_TAG: ${{ github.sha }}
```

Logs
```
Run digitalocean/app_action/deploy@v2
  with:
    token: ***
    app_spec_location: .do/api.yaml
    app_name: hidden
    print_build_logs: false
    print_deploy_logs: false
    deploy_pr_preview: false
  env:
    VERCEL_ORG_ID: ***
    VERCEL_PROJECT_ID: ***
    GHCR_TAG: ***

app "hidden" already exists, updating...
wait for deployment to finish
deployment is in phase: DEPLOYING
deployment is in phase: ACTIVE
App is now live under URL: hidden
```
