### ISSUE TITLE
Action is triggering two deploys

### ISSUE THREAD

**Issue by bwestover** [digitalocean/app_action#5]
It seems that this action is triggering two deploys each time I run it:

![image](https://user-images.githubusercontent.com/1987494/151595588-fe17dd1a-f2ef-461f-ae9c-004ec976f9ea.png)

I'm using a worker component that is deployed from DOCR.

It looks like what is happening is that it correctly sets the new image tag, which **automatically** triggers a deploy, and then it also triggers a force deploy 1 second later. This cancels the first deploy, and the second manual deploy works.

Is the forced deploy necessary if the App automatically deploys on a change to the App Spec?

My action looks like this:
```
  Deploy:
    needs: Build
    if: github.ref_name == 'main'
    runs-on: ubuntu-20.04
    name: Deploy to DigitalOcean App
    steps:
      - name: Set Environment
        run: |
          if [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            echo "SHA=$GITHUB_SHA" >> "$GITHUB_ENV"
          else
            echo "SHA=${{ github.event.pull_request.head.sha }}" >> "$GITHUB_ENV"
          fi
      - name: Deploying latest image
        uses: digitalocean/app_action@main
        with:
          app_name: my-app-name
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          images: '[
            {
            "name": "worker-name",
            "repository": "registry.digitalocean.com/registry-name/container-name",
            "tag": "${{ env.SHA }}"
            }
            ]'
```

App Spec:
```
name: my-app-name
region: nyc
workers:
- envs:
  - key: <redacted>
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:v<redacted>]
  image:
    registry_type: DOCR
    repository: registry-name
    tag: 436ec6e9b9d02b1ae59f71aadb091f06152905d9
  instance_count: 1
  instance_size_slug: basic-s
  name: worker-name
  run_command: <redacted>
```
