### ISSUE TITLE
retrieving active deployment: error in retrieving currently deployed app id: exit status 1

### ISSUE THREAD

**Issue by JoshuaM1995** [digitalocean/app_action#56]
I'm using this script but am getting the following error:

`retrieving active deployment: error in retrieving currently deployed app id: exit status 1`

Here's the environment variables in my github action:
```
env:
  CONTAINER_REGISTRY: "registry.digitalocean.com/***"
  WEB_IMAGE_NAME: "***_${{ github.ref_name }}"
  API_IMAGE_NAME: "***_${{ github.ref_name }}"
  TAG_NAME: 0.0.2
```

Here's the `digitalocean/app_action@v1.1.4` code in the github action:
```
with:
          app_name: ***-${{ github.ref_name }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[
            {
            "name": "***",
            "image":{
            "registry_type": "DOCR",
            "repository": "${{ env.CONTAINER_REGISTRY }}/${{ env.API_IMAGE_NAME }}",
            "tag": "${{ env.TAG_NAME }}"
            },
            ]'
```

Here is my Digital ocean app spec:
```
name: ***
region: ***
services:
  - name: ***
    image:
      registry_type: DOCR
      repository: ***
      deploy_on_push:
        enabled: false
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: ***
    routes:
      - path: /***
```

I tried everything, even looking at the go code. I noticed it runs this command: `doctl apps get-deployment`. Is there something I am doing wrong in my github actions file, but not triggering a digital ocean deployment? I assumed this script would do that for me.
