### ISSUE TITLE
retrieving active deployment: error in retrieving currently deployed app id: exit status 1

### ISSUE THREAD

**Issue by adamtay** [digitalocean/app_action#70]
Reporting same issue as #56 which was closed due to inactivity.

I'm getting the following error message:
```
2023/07/02 11:21:46 updating app spec: unable to update app: exit status 1
doctl apps update ce2efcab-cf41-4232-bce8-f5c5e93b030e --spec /tmp/_do_app_1731289123.yaml
```

With the following usage when deploying multiple images:
```
- uses: digitalocean/app_action@v1.1.5
  with:
    app_name: app-name-in-do
    token: ${{ secrets.DO_ACCESS_TOKEN }}
    images: '[
        {
           "name": "component-api",
           "image": {
              "registry_type": "DOCR",
              "repository": "registry.digitalocean.com/app-name-in-do/component-api",
              "tag": "sha-1234567"
           }
        },
        {
          "name": "component-client",
          "image": {
              "registry_type": "DOCR",
              "repository": "registry.digitalocean.com/app-name-in-do/component-client",
              "tag": "sha-1234567"
          }
        }
      ]'
```

I confirm that the app and component already exists in DO. This was working about 2 months ago for us.

**Comment by olivbau** [comment]
Same problem here:

```
name: Deploy on DO

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: digitalocean/app_action@v1.1.5
        with:
          app_name: ${{ secrets.DIGITALOCEAN_APP_NAME }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

```
