### ISSUE TITLE
unable to create-deployment for app

### ISSUE THREAD

**Issue by WFA-juliver** [digitalocean/app_action#79]
followed the steps but github action failed and getting this error `triggering deploy: unable to create-deployment for app: exit status 1`

any idea?

my app spec at **.do/app.yaml**

```
name: testapp
region: sgp
services:
- git:
    branch: main
    repo_clone_url: https://github.com/Web-Fuel-Agency-LTD/test-deploy-do.git
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: web
  routes:
  - path: /
```

and I tested it through app platform set up and I can create the app successfully.
